# include <stdio.h>
# include <sqlite3.h>
/*
	* Include SQLite 3 library
	* I might include a make file for linking or
	* just a .sh file with the compile-link-run command
**/
int main(){
	// Initialize sqlite3 database 
	// The SQLite3 database object is responsible for creating a connection
	// to the database file and for executing SQL statements on the db
	sqlite3 *db;
	// Initialize a variable for storing the return codes of the sqlite3 function calls
	// Typical return codes include the following
	/*
		* SQLite Return Codes:
 		* 
 		* Return Code   Macro Name        Description
 		* ------------------------------------------------------------
 		* 0             SQLITE_OK         Operation completed successfully.
 		* 1             SQLITE_ERROR      SQL error or missing database.
 		* 2             SQLITE_INTERNAL   Internal logic error in SQLite.
 		* 3             SQLITE_PERM       Access permission denied.
 		* 5             SQLITE_BUSY       The database file is locked.
 		* 6             SQLITE_LOCKED     A table in the database is locked.
 		* 7             SQLITE_NOMEM      A malloc() failed.
 		* 14            SQLITE_CANTOPEN   Unable to open the database file.
 		* 21            SQLITE_MISUSE     Library used incorrectly.
 		* 100           SQLITE_ROW        A result row is available (used with sqlite3_step()).
 		* 101           SQLITE_DONE       SQL statement execution is complete (used with sqlite3_step()).
 	*/
	int rc;
	// Open the database connection with sqlite3_open()
	// The function requres two arguments; 
	// 	1. The name of the database file
	//	2. The sqlite3 database object
	/*
		* The sqlite3_open function is used to open a connection to an SQLite database file.
 		* Purpose, syntax, behavior, and common use cases:
		*
 		* Purpose:
 		* - To establish a connection to an SQLite database file.
 		* - If the specified database file does not exist, SQLite will attempt to create it.
 		* - Returns a pointer to a database connection object (sqlite3*) that can be used
 		*   for subsequent database operations.
 		*
 		* Function Signature:
 		* int sqlite3_open(const char *filename, sqlite3 **ppDb);
 		*
 		* Parameters:
 		* 1. filename:
 		*    - The name of the database file to open or create.
 		*    - Special values:
 		*      - ":memory:": Creates a temporary in-memory database.
 		*      - "file::memory:?cache=shared": Creates a shared in-memory database.
 		*    - Can include URI parameters if URI support is enabled in SQLite.
 		* 
 		* 2. ppDb:
 		*    - A pointer to a pointer to an sqlite3 object.
 		*    - On success, this pointer is set to the database connection object.
 		*    - On failure, it is set to NULL.
 		*
 		* Return Value:
 		* - An integer that represents the success or failure of the operation.
 		* - Common return codes:
 		*   - SQLITE_OK (0): Success.
 		*   - SQLITE_CANTOPEN (14): The database file could not be opened.
 		*   - SQLITE_NOMEM (7): Memory allocation failed.
 		*   - SQLITE_ERROR (1): A general error occurred.
 	*/
	rc = sqlite3_open("startrektime.db",&db);
	printf("Attempted to open sqlite database: response code %d\n", rc);
	if (rc != SQLITE_OK){
		/*
 			* The sqlite3_errmsg() function is a part of the SQLite library and is used to retrieve 
 			* a human-readable string describing the most recent error that occurred in a database connection.
 			*
 			* Function Signature:
 			* const char *sqlite3_errmsg(sqlite3 *db);
 			*
 			* Purpose:
 			* - Provides detailed error messages to help developers diagnose issues with database operations.
 			* - Useful for debugging or logging when an SQLite function returns an error code.
 			*
 			* Parameters:
 			* 1. sqlite3 *db:
 			*    - A pointer to the database connection object for which the error message is retrieved.
 			*    - This must be the same connection object that experienced the error.
 			*
 			* Return Value:
 			* - A const char* pointer to a null-terminated UTF-8 string containing the error message.
 			* - The error message is generated by SQLite and is specific to the database connection provided.
 			*
 			* Behavior:
 			* - Scope:
 			*   - The error message pertains to the last API call on the given database connection (db) that failed.
 			*   - If no error has occurred, sqlite3_errmsg() returns "not an error".
 			* 
 			* - Memory:
 			*   - The string returned is managed by SQLite and remains valid until the next API call on the 
 			*     same database connection.
 			*   - Do not free or modify the returned string.
 		*/
		printf("Failed to open database file: Error %s\n", sqlite3_errmsg(db));
		// ALWAYS CLOSE THE DATABASE CONNECTION WITH: sqlite3_close(db);
		/*
 			* The sqlite3_close() function is used to close a connection to an SQLite database 
 			* and free all associated resources. It is a crucial part of managing the lifecycle 
 			* of a database connection to ensure proper cleanup and prevent resource leaks.
 			*
 			* Function Signature:
 			* int sqlite3_close(sqlite3 *db);
 			*
 			* Purpose:
 			* - To close a database connection that was previously opened using sqlite3_open() 
 			*   or sqlite3_open_v2().
 			* - Ensures that all resources, including memory allocations and file handles, are released.
 			* - Prevents database file corruption by ensuring that any pending changes are properly finalized.
 			*
 			* Parameters:
 			* 1. sqlite3 *db:
 			*    - A pointer to the database connection object to close.
 			*    - Must be a valid database connection that was opened earlier.
 			*    - If db is NULL, the function does nothing and returns SQLITE_OK.
 			*
 			* Return Value:
 			* - An integer indicating the result of the operation:
 			*   - SQLITE_OK (0): The database connection was successfully closed.
 			*   - SQLITE_BUSY (5): The connection could not be closed because there are 
 			*     unfinalized prepared statements, active transactions, or other resources still in use.
	 	*/

		int close_rc = sqlite3_close(db);
		printf("Closing db with result code: %d\n", close_rc);
		return rc;
	} else {
		printf("Open Database Successfully, can start reading/writing to db file");
		int close_rc = sqlite3_close(db);
		printf("Closing db with result code: %d\n", close_rc);
		return 0;
	}
}

